name: Build LaTeX document

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install TeX Live and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-luatex \
            texlive-lang-japanese \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            latexmk \
            fonts-ipafont \
            fonts-ipaexfont \
            fonts-dejavu

      - name: Compile LaTeX document
        working-directory: tex
        run: |
          latexmk -lualatex -synctex=1 -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: build/pdf/main.pdf
          if-no-files-found: error
